import type { ApprovalRequest } from '@/types';

export const MOCK_APPROVAL_REQUESTS: ApprovalRequest[] = [
  {
    id: 'app-001',
    vendorId: 'vnd-004',
    vendorName: 'Nexus Cloud Consulting',
    vendorCode: 'VND-2024-004',
    category: 'Services',
    submittedAt: '2026-08-11T10:00:00.000Z',
    status: 'pending',
    currentLevel: 2,
    totalLevels: 3,
    priority: 'high',
    taxId: 'GB-123456789',
    city: 'London',
    country: 'United Kingdom',
    complianceScore: 85,
    timeline: [
      {
        level: 1,
        title: 'Legal & Tax Verification',
        role: 'Legal Compliance Officer',
        approverName: 'Elena Rostova',
        status: 'approved',
        updatedAt: '2026-08-11T14:20:00.000Z',
        comments: 'W-9 and VAT certificates verified against UK Companies House records.',
      },
      {
        level: 2,
        title: 'Financial & Banking Audit',
        role: 'Senior Finance Lead',
        approverName: 'Marcus Vance',
        status: 'pending',
        comments: 'Evaluating banking settlement routing and Net 30 payment terms.',
      },
      {
        level: 3,
        title: 'Procurement Executive Approval',
        role: 'Chief Procurement Officer',
        approverName: 'David Chen',
        status: 'pending',
      },
    ],
    comments: [
      {
        id: 'c-101',
        authorName: 'Elena Rostova',
        authorRole: 'Legal Compliance Lead',
        timestamp: '2026-08-11T14:20:00.000Z',
        action: 'approved',
        stepTitle: 'Legal & Tax Verification',
        text: 'All legal documents, non-disclosure agreements, and tax IDs passed background verification with zero red flags.',
      },
      {
        id: 'c-102',
        authorName: 'Marcus Vance',
        authorRole: 'Finance Auditor',
        timestamp: '2026-08-12T09:15:00.000Z',
        action: 'commented',
        stepTitle: 'Financial & Banking Audit',
        text: 'Reviewing IBAN routing details for European wire transfers. Standard Net 30 terms confirmed.',
      },
    ],
  },
  {
    id: 'app-002',
    vendorId: 'vnd-010',
    vendorName: 'Pacific Rim Packaging',
    vendorCode: 'VND-2024-010',
    category: 'Manufacturing',
    submittedAt: '2026-08-10T08:30:00.000Z',
    status: 'changes_requested',
    currentLevel: 1,
    totalLevels: 3,
    priority: 'medium',
    taxId: 'JP-9010001012345',
    city: 'Tokyo',
    country: 'Japan',
    complianceScore: 78,
    timeline: [
      {
        level: 1,
        title: 'Legal & Tax Verification',
        role: 'Legal Compliance Officer',
        approverName: 'Sarah Jenkins',
        status: 'changes_requested',
        updatedAt: '2026-08-11T11:00:00.000Z',
        comments: 'Requested updated ISO 14001 Environmental Certificate copy.',
      },
      {
        level: 2,
        title: 'Financial & Banking Audit',
        role: 'Senior Finance Lead',
        approverName: 'Marcus Vance',
        status: 'pending',
      },
      {
        level: 3,
        title: 'Procurement Executive Approval',
        role: 'Chief Procurement Officer',
        approverName: 'David Chen',
        status: 'pending',
      },
    ],
    comments: [
      {
        id: 'c-201',
        authorName: 'Sarah Jenkins',
        authorRole: 'Compliance Lead',
        timestamp: '2026-08-11T11:00:00.000Z',
        action: 'requested_changes',
        stepTitle: 'Legal & Tax Verification',
        text: 'The submitted ISO environmental certificate expired last month. Please upload the renewed 2026 certification PDF.',
      },
    ],
  },
  {
    id: 'app-003',
    vendorId: 'vnd-017',
    vendorName: 'Zeta Robotics Labs',
    vendorCode: 'VND-2024-017',
    category: 'Technology',
    submittedAt: '2026-08-09T16:00:00.000Z',
    status: 'on_hold',
    currentLevel: 2,
    totalLevels: 3,
    priority: 'high',
    taxId: 'KR-1208112345',
    city: 'Seoul',
    country: 'South Korea',
    complianceScore: 90,
    timeline: [
      {
        level: 1,
        title: 'Legal & Tax Verification',
        role: 'Legal Compliance Officer',
        approverName: 'Elena Rostova',
        status: 'approved',
        updatedAt: '2026-08-10T10:00:00.000Z',
        comments: 'Korean corporate registration and SOC2 report verified.',
      },
      {
        level: 2,
        title: 'Financial & Banking Audit',
        role: 'Senior Finance Lead',
        approverName: 'Marcus Vance',
        status: 'on_hold',
        updatedAt: '2026-08-11T16:45:00.000Z',
        comments: 'On hold pending approval of international escrow payment terms.',
      },
      {
        level: 3,
        title: 'Procurement Executive Approval',
        role: 'Chief Procurement Officer',
        approverName: 'David Chen',
        status: 'pending',
      },
    ],
    comments: [
      {
        id: 'c-301',
        authorName: 'Marcus Vance',
        authorRole: 'Finance Auditor',
        timestamp: '2026-08-11T16:45:00.000Z',
        action: 'on_hold',
        stepTitle: 'Financial & Banking Audit',
        text: 'Placed on hold. Vendor is requesting 50% advance payment. Waiting for Treasury Board approval on escrow terms.',
      },
    ],
  },
  {
    id: 'app-004',
    vendorId: 'vnd-001',
    vendorName: 'Acme Global Logistics',
    vendorCode: 'VND-2024-001',
    category: 'Logistics',
    submittedAt: '2026-08-01T09:00:00.000Z',
    status: 'approved',
    currentLevel: 3,
    totalLevels: 3,
    priority: 'high',
    taxId: 'US-984321045',
    city: 'Chicago',
    country: 'United States',
    complianceScore: 98,
    timeline: [
      {
        level: 1,
        title: 'Legal & Tax Verification',
        role: 'Legal Compliance Officer',
        approverName: 'Elena Rostova',
        status: 'approved',
        updatedAt: '2026-08-01T14:00:00.000Z',
      },
      {
        level: 2,
        title: 'Financial & Banking Audit',
        role: 'Senior Finance Lead',
        approverName: 'Marcus Vance',
        status: 'approved',
        updatedAt: '2026-08-02T10:00:00.000Z',
      },
      {
        level: 3,
        title: 'Procurement Executive Approval',
        role: 'Chief Procurement Officer',
        approverName: 'David Chen',
        status: 'approved',
        updatedAt: '2026-08-02T16:00:00.000Z',
        comments: 'Fully approved as primary Midwest freight partner.',
      },
    ],
    comments: [
      {
        id: 'c-401',
        authorName: 'David Chen',
        authorRole: 'CPO',
        timestamp: '2026-08-02T16:00:00.000Z',
        action: 'approved',
        stepTitle: 'Procurement Executive Approval',
        text: 'Final executive sign-off granted. Vendor account set to Active with Net 30 terms.',
      },
    ],
  },
  {
    id: 'app-005',
    vendorId: 'vnd-013',
    vendorName: 'Omni Media Operations',
    vendorCode: 'VND-2024-013',
    category: 'Services',
    submittedAt: '2026-07-15T09:00:00.000Z',
    status: 'rejected',
    currentLevel: 1,
    totalLevels: 3,
    priority: 'low',
    taxId: 'US-334455667',
    city: 'Los Angeles',
    country: 'United States',
    complianceScore: 35,
    timeline: [
      {
        level: 1,
        title: 'Legal & Tax Verification',
        role: 'Legal Compliance Officer',
        approverName: 'Elena Rostova',
        status: 'rejected',
        updatedAt: '2026-07-16T12:00:00.000Z',
        comments: 'Failed IP compliance and legal audit.',
      },
      {
        level: 2,
        title: 'Financial & Banking Audit',
        role: 'Senior Finance Lead',
        status: 'pending',
      },
      {
        level: 3,
        title: 'Procurement Executive Approval',
        role: 'Chief Procurement Officer',
        status: 'pending',
      },
    ],
    comments: [
      {
        id: 'c-501',
        authorName: 'Elena Rostova',
        authorRole: 'Legal Compliance Lead',
        timestamp: '2026-07-16T12:00:00.000Z',
        action: 'rejected',
        stepTitle: 'Legal & Tax Verification',
        text: 'Application rejected due to active copyright litigation and breach of prior contract terms.',
      },
    ],
  },
];
