import type { KanbanVendorCard } from '@/types';

export const MOCK_KANBAN_CARDS: KanbanVendorCard[] = [
  {
    id: 'kan-001',
    vendorCode: 'VND-2024-004',
    vendorName: 'Nexus Cloud Consulting',
    category: 'Services',
    contactPerson: 'Elena Rostova',
    city: 'London',
    country: 'United Kingdom',
    complianceScore: 85,
    submittedDate: '2026-08-11T10:00:00.000Z',
    stage: 'finance_audit',
    priority: 'high',
  },
  {
    id: 'kan-002',
    vendorCode: 'VND-2024-010',
    vendorName: 'Pacific Rim Packaging',
    category: 'Manufacturing',
    contactPerson: 'Sarah Jenkins',
    city: 'Tokyo',
    country: 'Japan',
    complianceScore: 78,
    submittedDate: '2026-08-10T08:30:00.000Z',
    stage: 'on_hold_revisions',
    priority: 'medium',
  },
  {
    id: 'kan-003',
    vendorCode: 'VND-2024-017',
    vendorName: 'Zeta Robotics Labs',
    category: 'Technology',
    contactPerson: 'Min-Jun Park',
    city: 'Seoul',
    country: 'South Korea',
    complianceScore: 90,
    submittedDate: '2026-08-09T16:00:00.000Z',
    stage: 'under_review',
    priority: 'high',
  },
  {
    id: 'kan-004',
    vendorCode: 'VND-2024-001',
    vendorName: 'Acme Global Logistics',
    category: 'Logistics',
    contactPerson: 'Robert Sterling',
    city: 'Chicago',
    country: 'United States',
    complianceScore: 98,
    submittedDate: '2026-08-01T09:00:00.000Z',
    stage: 'approved_onboarded',
    priority: 'high',
  },
  {
    id: 'kan-005',
    vendorCode: 'VND-2024-002',
    vendorName: 'Apex Semiconductor Systems',
    category: 'Technology',
    contactPerson: 'Dr. Aris Thorne',
    city: 'Austin',
    country: 'United States',
    complianceScore: 95,
    submittedDate: '2026-08-02T11:00:00.000Z',
    stage: 'approved_onboarded',
    priority: 'medium',
  },
  {
    id: 'kan-006',
    vendorCode: 'VND-2026-099',
    vendorName: 'Quantum Dynamics Tech',
    category: 'Services',
    contactPerson: 'Claire Bennett',
    city: 'San Francisco',
    country: 'United States',
    complianceScore: 62,
    submittedDate: '2026-08-12T14:20:00.000Z',
    stage: 'draft_submitted',
    priority: 'low',
  },
];
