import type { VendorNotification } from '@/types';

export const MOCK_NOTIFICATIONS: VendorNotification[] = [
  {
    id: 'notif-001',
    title: 'Approval Pending – Finance Audit Gate',
    message: 'Nexus Cloud Consulting (VND-2024-004) is awaiting Level 2 Financial & Banking audit approval.',
    category: 'approval_pending',
    priority: 'urgent',
    vendorId: 'vnd-004',
    vendorName: 'Nexus Cloud Consulting',
    timestamp: '2026-08-13T09:15:00.000Z',
    isRead: false,
    actionUrl: '/approvals',
    actionLabel: 'Review Request',
  },
  {
    id: 'notif-002',
    title: 'Document Expiring – ISO Environmental Certificate',
    message: 'ISO 14001 Environmental Compliance Certificate for Pacific Rim Packaging expires in 7 days (Aug 20, 2026).',
    category: 'document_expiring',
    priority: 'high',
    vendorId: 'vnd-010',
    vendorName: 'Pacific Rim Packaging',
    timestamp: '2026-08-13T07:45:00.000Z',
    isRead: false,
    actionUrl: '/vendors/vnd-010',
    actionLabel: 'View Documents',
  },
  {
    id: 'notif-003',
    title: 'Low Vendor Rating Alert',
    message: 'Vortex Industrial Materials performance score dropped to 2.1 / 5.0 due to recurring 18.5h response delay.',
    category: 'low_vendor_rating',
    priority: 'high',
    vendorId: 'vnd-003',
    vendorName: 'Vortex Industrial Materials',
    timestamp: '2026-08-12T16:30:00.000Z',
    isRead: false,
    actionUrl: '/performance',
    actionLabel: 'Open Scorecard',
  },
  {
    id: 'notif-004',
    title: 'Delayed Shipment Alert – PO #8901',
    message: 'Freight shipment #PO-8901 for Acme Global Logistics delayed by 48 hours on Midwest logistics corridor.',
    category: 'delayed_delivery',
    priority: 'medium',
    vendorId: 'vnd-001',
    vendorName: 'Acme Global Logistics',
    timestamp: '2026-08-12T11:20:00.000Z',
    isRead: true,
    actionUrl: '/vendors/vnd-001',
    actionLabel: 'Check PO Details',
  },
  {
    id: 'notif-005',
    title: 'Payment Due Warning – Invoice #INV-2026-901',
    message: 'Invoice #INV-2026-901 of $42,500 for Apex Semiconductor Systems is due for settlement in 3 days.',
    category: 'payment_due',
    priority: 'medium',
    vendorId: 'vnd-002',
    vendorName: 'Apex Semiconductor Systems',
    timestamp: '2026-08-11T14:00:00.000Z',
    isRead: false,
    actionUrl: '/performance',
    actionLabel: 'View Invoicing',
  },
  {
    id: 'notif-006',
    title: 'Document Expiring – W-9 Tax Certification',
    message: 'Annual W-9 tax certificate renewal required for Delta Freight Corp within 14 days.',
    category: 'document_expiring',
    priority: 'low',
    vendorId: 'vnd-005',
    vendorName: 'Delta Freight Corp',
    timestamp: '2026-08-10T10:00:00.000Z',
    isRead: true,
    actionUrl: '/vendors/vnd-005',
    actionLabel: 'View Vendor Profile',
  },
];
